# Generated by Django 5.1.5 on 2025-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_prompt', models.TextField()),
                ('generated_prompt', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(verbose_name='auth.User')),
            ],
        ),
    ]
